//LOCATION TYPES
//All Cities
export const CITIES = "CITIES";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const GET_CITIES_FAILURE = "GET_CITIES_FAILURE";


//Selected City
export const SELECTED_CITY = "SELECTED_CITY";
export const GET_SELECTED_CITY_SUCCESS = "GET_SELECTED_CITY_SUCCESS";
export const GET_SELECTED_CITY_FAILURE = "GET_SELECTED_CITY_FAILURE";